### PR TITLE
update for mpw8

### PR DESCRIPTION
**Pull request by proppy**
- update to https://github.com/efabless/caravel_user_project/ main branch
- update la and power pins

### CODE REVIEW

**Comment by radhe-2022** [comment]
Sir how to update to updated commits on local system?

**Comment by proppy** [comment]
@radhe-2022 on a existing project? You could apply the patch locally: 
https://github.com/proppy/tiny_user_project/pull/24.patch

**Comment by proppy** [comment]
@t-sasatani confirmed that the template works for his project:
https://github.com/t-sasatani/xls_workshop_tapeout_test_all_branch/actions/runs/3712018428

**Comment by proppy** [comment]
Merging so we can validate the flow at the next workshop: https://github.com/chipsalliance/silicon-notebooks/pull/37

**Pull request merged**
