### PR TITLE
cherry pick gf180mcu caravel_user_project changes

### PR DESCRIPTION
**Pull request by proppy**
- cherry-pick https://github.com/efabless/caravel_user_project/commit/6aebd52ec9b06ad6a126ff91cb32e9d2cbf131ce
- ~~cherry-pick https://github.com/efabless/caravel_user_project/commit/17bbec35943e3072832f66aaa683693d95c21227~~
- fix conflicts
- keep JSON configuration for `tiny_user_project`
- forward all wrapper pins
- expand macro size
- bump clock period

### CODE REVIEW

**Comment by proppy** [comment]
@urish @shaos @jeffdi FYI

**Comment by urish** [comment]
What if we don't?

**Comment by proppy** [comment]
> what if we don't?

maybe @jeffdi can comment how critical https://github.com/efabless/caravel_user_project/commit/6aebd52ec9b06ad6a126ff91cb32e9d2cbf131ce and https://github.com/efabless/caravel_user_project/commit/17bbec35943e3072832f66aaa683693d95c21227 are?

**Comment by proppy** [comment]
no more lvs error:
https://github.com/proppy/tiny_user_project/actions/runs/3583804867/jobs/6029677445
but precheck now fails with:
```
{{STEP UPDATE}} Executing Check 3 of 4: Klayout BEOL
Traceback (most recent call last):
  File "mpw_precheck.py", line 141, in <module>
    default_content='_default_content')
  File "mpw_precheck.py", line 102, in main
    run_precheck_sequence(precheck_config=precheck_config, project_config=project_config)
  File "mpw_precheck.py", line 68, in run_precheck_sequence
    results[check.__surname__] = check.run()
  File "/home/runner/mpw_precheck/check_manager/__init__.py", line 156, in run
    self.klayout_cmd_extra_args)
  File "/home/runner/mpw_precheck/checks/drc_checks/klayout/klayout_gds_drc_check.py", line 20, in klayout_gds_drc_check
    with open(report_file_path) as klayout_xml_report:
FileNotFoundError: [Errno 2] No such file or directory: 
```

**Comment by proppy** [comment]
rebased and removed generated file from the commit.

**Comment by proppy** [comment]
I think this is the intersection of the changes in https://github.com/efabless/caravel_user_project/pull/206
 and the performance issue in https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/1 that is making the action timeout and fail precheck.

**Comment by proppy** [comment]
Disable running precheck in the actions with 799a086 as https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/1 make it blow up memory for non-trival project.

**Comment by proppy** [comment]
Reset https://github.com/proppy/tiny_user_project_inverter to this branch, and re-submiting it to https://platform.efabless.com/projects/1608 to validate that the precheck are passing on the efabless platform.

**Comment by proppy** [comment]
rebased the changes, will merge once I confirm https://github.com/proppy/tiny_user_project/pull/10#issuecomment-1334638031

**Comment by proppy** [comment]
```
[12/01/22 17:02:10 PST] STEP UPDATE
Executing Check 2 of 4: Klayout FEOL






[12/01/22 17:13:55 PST] KLAYOUT FEOL CHECK PASSED
The GDS file, user_project_wrapper.gds, has no DRC violations.
```
pre-check do pass on the platform \o/

**Pull request merged**
